- hosts: wordpress_servers
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-xml
          - php-gd
          - php-mbstring
          - python3-pymysql
          - python3-mysqldb
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: yes
        
    - name: Ensure MySQL admin user exists
      mysql_user:
        name: admin
        password: "password"
        priv: ".:ALL,GRANT"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress Database
      mysql_db:
        name: wordpress
        state: present
        login_user: admin
        login_password: "password"

    - name: Create WordPress User
      mysql_user:
        name: wp-user
        password: "password"
        priv: 'wordpress.*:ALL'
        host: "%"
        state: present
        login_user: admin
        login_password: "password"

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress into /var/www/html
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes
    
    - name : delete default apache file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Restart Apache
      service:
        name: apache2
        state: restarted